# Generated by Django 3.2 on 2021-04-27 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='state',
            field=models.CharField(choices=[('O', 'open'), ('A', 'archived')], default='O', max_length=1),
        ),
    ]
