name: Build and Deploy stable
on:
  release:
    types: [published]
jobs:
  build-and-depoly-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: update version
        run: echo ${{ github.event.release.name }} > src/version.txt
      - name: commit new version
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "Chessmasterrr@users.noreply.github.com"
          git add src/version.txt
          git commit -m "automatic update of version file" && git push origin HEAD:master || echo "No changes to commit"
      - name: Build and push stable Docker image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: opinioxx/stable
          tags: latest, ${{ github.event.release.name }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Update Service
        run: aws ecs update-service --force-new-deployment --cluster sf-cluster --service sf-service
