name: Build and Deploy stable
on:
  release:
    types: [published]
jobs:
  build-and-depoly-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: update version
        run: echo ${{ github.event.release.name }} > src/version.txt
      - name: commit new version
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "Chessmasterrr@users.noreply.github.com"
          git add src/version.txt
          git commit -m "automatic update of version file" && git push origin HEAD:master || echo "No changes to commit"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push development Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          pull: true
          push: true
          cache-from: type=registry,ref=opinioxx/stable:latest
          cache-to: type=inline
          tags: opinioxx/stable:latest, opinioxx/stable:${{ github.event.release.name }}
      - name: Checkout code
        uses: actions/checkout@v2
